Entity/ShoppingOrder.php
<?php

namespace Megacoders\ShoppingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Megacoders\ShoppingBundle\Model\ShoppingProduct;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Megacoders\AdminBundle\Entity\User;


/**
 * @ORM\Entity
 * @ORM\Table(name="shopping_order")
 */
class ShoppingOrder
{
    const DATE_FORMAT = 'Y-m-d H:i:s';

    const STATUS_CREATED = 'CREATED';

    const STATUS_CANCELED = 'CANCELED';

    const STATUS_CONFIRMED = 'CONFIRMED';

    const STATUS_PAID = 'PAID';

    const STATUS_PENDING = 'PENDING';

    const STATUSES_NAMES = [
        self::STATUS_CREATED => 'admin.entities.shopping_order.status_created',
        self::STATUS_CANCELED => 'admin.entities.shopping_order.status_canceled',
        self::STATUS_PAID => 'admin.entities.shopping_order.status_paid',
        self::STATUS_CONFIRMED => 'admin.entities.shopping_order.status_confirmed',
        self::STATUS_PENDING => 'admin.entities.shopping_order.status_pending'
    ];

    const PARAMETER_LOCALE = 'locale';

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @var \DateTime
     */
    private $date;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @var string
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="ShoppingAccount", cascade={"persist"})
     * @Assert\NotBlank()
     * @var ShoppingAccount
     */
    private $account;

    /**
     * @ORM\OneToMany(targetEntity="ShoppingOrderItem", mappedBy="order", cascade={"persist"}, orphanRemoval=true)
     * @var ArrayCollection
     */
    private $items;

    /**
     * @ORM\ManyToOne(targetEntity="Megacoders\AdminBundle\Entity\User")
     * @var User
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="ShoppingPayment", mappedBy="order", orphanRemoval=true)
     * @var ArrayCollection
     */
    private $payments;

    /**
     * @ORM\Column(type="array", nullable=true)
     * @var array
     */
    private $parameters = [];

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank()
     * @var float
     */
    private $price = 0;

    /**
     * ShoppingOrder constructor.
     */
    public function __construct()
    {
        $this->date = new \DateTime();
        $this->status = self::STATUS_CREATED;
        $this->items = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return ShoppingOrder
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param \DateTime $date
     * @return ShoppingOrder
     */
    public function setDate(\DateTime $date)
    {
        $this->date = $date;
        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return string|null
     */
    public function getStatusName()
    {
        $types = self::STATUSES_NAMES;

        if (isset($types[$this->getStatus()])) {
            return $types[$this->getStatus()];
        }

        return null;
    }

    /**
     * @param string $status
     * @return ShoppingOrder
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return ShoppingAccount
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * @param ShoppingAccount $account
     * @return ShoppingOrder
     */
    public function setAccount(ShoppingAccount $account)
    {
        $this->account = $account;
        return $this;
    }

    /**
     * @return ArrayCollection|ShoppingProduct[]
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * @param ArrayCollection $items
     * @return ShoppingOrder
     */
    public function setItems(ArrayCollection $items)
    {
        $this->items->clear();

        foreach ($items as $item) {
            $this->addItem($item);
        }

        return $this;
    }

    /**
     * @param ShoppingOrderItem $item
     * @return ShoppingOrder
     */
    public function addItem(ShoppingOrderItem $item)
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setOrder($this);
        }

        return $this;
    }

    /**
     * @param ShoppingOrderItem $item
     * @return ShoppingOrder
     */
    public function removeItem(ShoppingOrderItem $item)
    {
        $this->items->removeElement($item);
        return $this;
    }

    /**
     * @return $this
     */
    public function removeAllItems()
    {
        $this->items->clear();
        return $this;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return ShoppingOrder
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return ShoppingOrder
     */
    public function setPrice($price)
    {
        $this->price = $price;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * @param ArrayCollection $payments
     * @return ShoppingOrder
     */
    public function setPayments(ArrayCollection $payments)
    {
        $this->payments->clear();

        foreach ($payments as $payment) {
            $this->addPayment($payment);
        }

        return $this;
    }

    /**
     * @param ShoppingPayment $payment
     * @return $this
     */
    public function addPayment(ShoppingPayment $payment)
    {
        if (!$this->payments->contains($payment)) {
            $this->payments->add($payment);
            $payment->setOrder($this);
        }

        return $this;
    }

    /**
     * @return array
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * @param string $name
     * @param mixed $default
     * @return mixed
     */
    function getParameter($name, $default = null)
    {
        return isset($this->parameters[$name]) ? $this->parameters[$name] : $default;
    }

    /**
     * @param array $parameters
     * @return ShoppingOrder
     */
    public function setParameters(array $parameters)
    {
        $this->parameters = $parameters;
        return $this;
    }

    /**
     * @param string $name
     * @param mixed $value
     * @return ShoppingOrder
     */
    public function setParameter($name, $value)
    {
        $this->parameters[$name] = $value;
        return $this;
    }

    /**
     * @param string $locale
     * @return ShoppingOrder
     */
    public function setLocale($locale)
    {
        $this->setParameter(self::PARAMETER_LOCALE, $locale);
        return $this;
    }

    /**
     * @return string
     */
    public function getLocale()
    {
        return $this->getParameter(self::PARAMETER_LOCALE);
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $date = $this->getDate();

        return $date ? $date->format(self::DATE_FORMAT) : '';
    }
}

Resources/views/Admin/ShoppingOrder/list.html.twig

{% extends 'SonataAdminBundle:CRUD:list.html.twig' %}

{% block list_table %}
    {{ parent() }}
    {{ block('order_list_modal') }}
    {{ block('order_list_js') }}
{% endblock %}

{% block order_list_modal %}
    <div class="modal fade" id="order_list__dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block order_list_js %}
    {% autoescape false %}

    <script type="text/javascript">

        var order_list_dialog         = false;
        var order_list_dialog_content = false;
        var order_list_dialog_title   = false;

        function order_list_initialize_popup() {
            // initialize component
            if (!order_list_dialog) {
                order_list_dialog         = jQuery("#order_list__dialog");
                order_list_dialog_content = jQuery(".modal-body", "#order_list__dialog");
                order_list_dialog_title   = jQuery(".modal-title", "#order_list__dialog");

                // move the dialog as a child of the root element, nested form breaks html ...
                jQuery(document.body).append(order_list_dialog);
            }
        }

        function start_dialog_form_add(link) {

            // remove the html event
            link.onclick = null;

            order_list_initialize_popup();

            // add the jQuery event to the a element
            jQuery(link)
                    .click(dialog_form_add)
                    .trigger('click')
            ;

            return false;
        }

        function start_dialog_delete(link) {

            // remove the html event
            link.onclick = null;

            order_list_initialize_popup();

            // add the jQuery event to the a element
            jQuery(link)
                    .click(dialog_form_add)
                    .trigger('click')
            ;

            return false;
        }

        // handle the add and delete link
        var dialog_form_add = function(event) {
            order_list_initialize_popup();

            event.preventDefault();
            event.stopPropagation();

            var a = jQuery(this);

            order_list_dialog_content.html('');

            // retrieve the form element from the related admin generator
            jQuery.ajax({
                url: a.attr('href'),
                dataType: 'html',
                success: function(html) {

                    // populate the popup container
                    order_list_dialog_content.html(html);
                    order_list_dialog_title.html(a.attr('title'));

                    Admin.shared_setup(order_list_dialog);

                    // capture the submit event to make an ajax call, ie : POST data to the
                    // related create admin
                    jQuery('a', order_list_dialog).on('click', dialog_form_action);
                    jQuery('form', order_list_dialog).on('submit', dialog_form_action);

                    // open the dialog in modal mode
                    order_list_dialog.modal();

                    Admin.setup_list_modal(order_list_dialog);
                }
            });
        };

        // handle the post data
        var dialog_form_action = function(event) {

            var element = jQuery(this);

            // return if the link is an anchor inside the same page
            if (
                    this.nodeName === 'A'
                    && (
                            element.attr('href').length === 0
                            || element.attr('href')[0] === '#'
                            || element.attr('href').substr(0, 11) === 'javascript:'
                    )
            ) {
                return;
            }

            event.preventDefault();
            event.stopPropagation();

            order_list_initialize_popup();

            if (this.nodeName == 'FORM') {
                var url  = element.attr('action');
                var type = element.attr('method');
            } else if (this.nodeName == 'A') {
                var url  = element.attr('href');
                var type = 'GET';
            } else {
                alert('unexpected element : @' + this.nodeName + '@');
                return;
            }

            var data = {
                _xml_http_request: true
            }

            var form = jQuery(this);

            // the ajax post
            jQuery(form).ajaxSubmit({
                url: url,
                type: type,
                data: data,
                success: function(data) {
                    // if the crud action return ok, then the element has been added
                    // so the widget container must be refresh with the last option available
                    if (typeof data != 'string' && data.result == 'ok') {
                        order_list_dialog.modal('hide');
                        location.reload();
                        return;
                    }

                    // otherwise, display form error
                    order_list_dialog_content.html(data);

                    Admin.shared_setup(order_list_dialog);

                    // reattach the event
                    jQuery('form', order_list_dialog).submit(dialog_form_action);
                }
            });

            return false;
        };


    </script>

    {% endautoescape %}
{% endblock %}

Resources/views/Admin/ShoppingOrder/list__account.html.twig
{% extends 'SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig' %}

{% block field %}
    {{ parent() }}
    {% if value.phone %} <br>{{ value.phone }} {% endif %}
    {% if value.email %} <br>{{ value.email }} {% endif %}

    {% if object.status != 'CANCELED' %}
        <p style="margin-top: 10px;">
            <a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('resendNotification', object) }}" title="{{ 'admin.entities.shopping_order.action_resend_notification'|trans }}">
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                {{ 'admin.entities.shopping_order.action_resend_notification'|trans }}
            </a>
        </p>
    {% endif %}

{% endblock %}

Resources/views/Admin/ShoppingOrder/list__date_and_number.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    <strong>#{{ object.id }}</strong><br>
    {{ object.date|date('Y-m-d H:i') }}<br>
    {% if object.status == 'CREATED' %}
        {% set class_name = 'warning' %}
    {% elseif object.status == 'PAID'  %}
        {% set class_name = 'success' %}
    {% elseif object.status == 'CONFIRMED'  %}
        {% set class_name = 'info' %}
    {% elseif object.status == 'CANCELED'  %}
        {% set class_name = 'secondary' %}
    {% endif %}
    <span class="badge btn-{{ class_name }}">{{ object.statusName|trans }}</span>
{% endblock %}

Resources/views/Admin/ShoppingOrder/list__items.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
{% for item in object.items %}
    <div>
        <strong>{{ item.name }}</strong>,
        {{ item.price|number_format_currency('EUR') }}{% if admin.isProductQuantityEditable(item) %}, {{ 'admin.entities.shopping_order_item.quantity'|trans }}: {{ item.quantity }}{% endif %}
        <br>
        {% for key, row in admin.getProductDescription(item) %}
            {% if row.type == 'boolean' %}
                {{ row.name|trans }}: {{ ('admin.values.boolean.' ~ (row.value ? 'yes' : 'no'))|trans }}
            {% elseif row.type == 'choice' %}
                {{ row.choice_label|transchoice(row.value, {'%count%': row.value}) }}
            {% else %}
                {{ row.value }}
            {% endif %}
            <br>
        {% endfor %}
    </div>
{% endfor %}
    <br>
    <p><strong>{{ 'admin.entities.shopping_order.total'|trans }}: {{ object.price|number_format_currency('EUR') }}</strong></p>
{% endblock %}

Resources/views/Admin/ShoppingOrder/list__payments.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    {% if object.payments|length %}

            {% for payment in object.payments %}
                {% set icon = '' %}
                {% if payment.method == 'PAYMENT_SERVICE' %}
                    {% set icon = 'fa-credit-card' %}
                {% elseif payment.method == 'CASH' %}
                    {% set icon = 'fa-money' %}
                {% endif %}
                <div style="clear: both; margin-bottom: 5px;">
                    <div style="text-align:right; display: inline-block; float: right; width: 45px; white-space: nowrap; position: relative;">
                        {% if payment.info|length %}
                        <div class="dropdown" style="display: inline-block;">
                            <a href="#" class="dropdown-toggle" id="dropdownInfo-{{ payment.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><i class="fa fa-info-circle" aria-hidden="true" style="padding: 0 5px;"></i></a>
                            <div class="dropdown-menu" style="padding-left: 5px; padding-right: 5px;" aria-labelledby="dropdownInfo-{{ payment.id }}">
                                <h5><strong>{{ 'admin.entities.shopping_payment.details'|trans }}</strong></h5>
                                {% for key,value in payment.info %}
                                    {% if key != 'userComment' %}{{ key }}: {% endif %}{{ value }}<br>
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}
                        <a onclick="return start_dialog_delete(this);" href="{{ admin.getRouteGenerator.generateUrl(field_description.getOption('paymentAdmin') , 'delete', {'id' : payment.id}) }}" title="{{ 'admin.actions.shopping_payment.delete_payment'|trans }}" data-id="{{ payment.id }}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                    </div>
                    <div style="margin-right: 50px;">
                        <i class="fa {{ icon }}" aria-hidden="true"></i>
                        <strong>{{ payment.amount|number_format_currency('EUR') }}</strong> <span style="white-space: nowrap;">at {{ payment.date|date('d M') }}</span>
                    </div>
                </div>
            {% endfor %}

    {% endif %}

    {% if object.status != 'CANCELED' %}
        <p style="margin-top: 5px;"><a onclick="return start_dialog_form_add(this);" href="{{ admin.getRouteGenerator.generateUrl(field_description.getOption('paymentAdmin') , 'create', {'order_id' : object.id}) }}" title="{{ 'admin.actions.shopping_payment.add_payment'|trans }}">{{ 'admin.actions.shopping_payment.add_payment'|trans }}</a></p>
    {% endif %}
{% endblock %}

Resources/views/Admin/ShoppingOrder/show__discount.html.twig
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    {% set discount = field_description.getOption('discount') %}
    {% if discount and discount|length %}
        {% for discountInfo in discount %}
            <p>{{ 'admin.entities.shopping_order.discount_value_is'|trans }} <strong>{{ discountInfo.value|number_format_currency('EUR') }}</strong>
            {% if discountInfo.promoCode %} {{ 'admin.entities.shopping_order.with_promo_code'|trans }} <strong>{{ discountInfo.promoCode }}</strong>{% endif %}</p>
        {% endfor %}
    {% else %}
        —
    {% endif %}
{% endblock %}

Resources/views/Admin/ShoppingOrder/show__items.html.twig
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    {% for item in value %}
        <div class="row">
            <div class="col-md-2">
                {% if item.image %}
                    <img src="{{ web_image(item.image).cropResize(150, 150) }}" class="img-thumbnail"/>
                {% endif %}
            </div>
            <div class="col-md-10">
                <p><strong>{{ item.name }}</strong></p>

                <div>{{ item.description|raw }}</div>

                <p>
                    {{ item.price|number_format_currency('EUR') }},
                    {{ 'admin.entities.shopping_order_item.quantity'|trans }}: {{ item.quantity }}
                </p>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>{{ 'admin.entities.shopping_order_item.parameter_key'|trans }}</th>
                            <th>{{ 'admin.entities.shopping_order_item.parameter_value'|trans }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for key, row in admin.getProductDescription(item) %}
                            <tr>
                                <td>{{ row.name|trans }}</td>
                                <td>
                                    {% if row.type == 'boolean' %}
                                        {{ ('admin.values.boolean.' ~ (row.value ? 'yes' : 'no'))|trans }}
                                    {% elseif row.type == 'choice' %}
                                        {{ row.choice_label|transchoice(row.value, {'%count%': row.value}) }}
                                    {% else %}
                                        {{ row.value }}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}
{% endblock %}

Resources/views/Admin/ShoppingOrder/show__payments.html.twig
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    {% if value|length %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{{ 'admin.entities.shopping_payment.date'|trans }}</th>
                    <th>{{ 'admin.entities.shopping_payment.amount'|trans }}</th>
                    <th>{{ 'admin.entities.shopping_payment.method'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for payment in value %}
                    <tr>
                        <td>{{ payment.date|date('d.m.Y H:i') }}</td>
                        <td>{{ payment.amount }}</td>
                        <td>{{ payment.method }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        —
    {% endif %}
{% endblock %}